services:
  backend:
    restart: always
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
    networks:
      - bus
    expose:
      - 3000
    deploy:
      mode: replicated
      replicas: 4
networks:
  bus:
